plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-webring
#  - jekyll-image-size
  

# SEO Stuff
title: "Joelchrono12.xyz"
author: "joelchrono12"
url: "https://joelchrono12.netlify.app"
baseurl: ""
#include: [".well-known"]
#

collections:
  origami:
    output: true

include:
  - _redirects

excludes:
  - _data/webring.yml
# RSS feeds
feed:
  posts_limit: 150
  collections: 
    origami:
      path: "/origami.xml"
  tags: 
    path: "feeds/"

webring:
  data_file: webring
  layout_file: webring
  feeds:
    - https://erzadel.net/feed.xml
    - https://chriswiegman.com/feed
    - https://lazybear.io/index.xml
    - https://kevq.uk/feed
    - https://jasonsanta.xyz/rss.xml
    - https://dusanmitrovic.xyz/rss
    - https://rusingh.com/category/post/article/feed/
  num_items: 5
  no_item_at_date_behaviour: use_latest
  date_format: "%B %-d, %Y"
