plugins:
  - jekyll-feed
  - jekyll-sitemap
#  - jekyll-webring
#  - jekyll-image-size
  

# SEO Stuff
title: "Joelchrono12's Blog"
author: joelchrono12
description: My personal blog, where I share my interests and hobbies
lang: en
timezone: America/Mexico_City
locale: en_US
highlighter: rouge
url: "https://joelchrono12.netlify.app"
baseurl: ""
#include: [".well-known"]
include:
  - _redirects
# RSS feeds
feed:
  posts_limit: 45
  tags: 
    path: "feeds/"
