plugins:
  #- jekyll-feed
  - jekyll-sitemap
  #- jekyll-webring
  - jekyll-redirect-from
#  - jekyll-image-size
  

# SEO Stuff
title: "Joel's Log Files"
author: 
  name: "joelchrono"
  twitter: "https://twitter.com/@joel"
  email: "joel.chrono@disroot.org"
url: "https://joelchrono.xyz"
baseurl: ""
timezone: "America/Mexico_City"
#include: [".well-known"]
#
#
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
whitelist:
  - jekyll-redirect-from

collections:
  posts:
    output: true
    permalink: /blog/:year-:month-:day-:title/
  origami:
    output: true

include:
  - tags
  - _redirects

excludes:
  - _data/webring.yml
# RSS feeds
feed_items: 20
feed:
  posts_limit: 20
  collections: 
    origami:
      path: "/origami.xml"
  tags: 
    path: "feeds/"

#webring:
  #data_file: webring
  #layout_file: webring
  #feeds:
    #- https://erzadel.net/feed.xml
    #- https://chriswiegman.com/feed
    #- https://lazybear.io/index.xml
    #- https://kevq.uk/feed
    #- https://jasonsanta.xyz/rss.xml
    #- https://dusanmitrovic.xyz/rss
    #- https://rusingh.com/category/post/article/feed/
  #num_items: 5
  ##no_item_at_date_behaviour: use_latest
  #date_format: "%B %-d, %Y"
