plugins:
  - jekyll-feed
  - jekyll-sitemap
#  - jekyll-webring
#  - jekyll-image-size
  

# SEO Stuff
title: "Joelchrono12's Blog"
author: joelchrono12
description: My personal blog, where I share my interests and hobbies
lang: en
timezone: America/Mexico_City
locale: en_US
url: "https://www.joelchrono12.ml"
baseurl: ""
include:
  - _redirects
  - .well-known
# RSS feeds
feed:
  posts_limit: 30
