plugins:
  - jekyll-feed
  - jekyll-sitemap
#  - jekyll-webring
#  - jekyll-image-size
  

# SEO Stuff
title: "Joelchrono12's Blog"
author: 
  name: joelchrono12
  email: joel.chrono@disroot.org
description: My personal blog, where I share my interests and hobbies
lang: en
timezone: America/Mexico_City
locale: en_US
highlighter: rouge
url: "https://joelchrono12.netlify.app"
baseurl: ""
#include: [".well-known"]
#

collections:
  origami:
    output: true

include:
  - _redirects
# RSS feeds
feed:
  posts_limit: 150
  collections: 
    origami:
      path: "/origami.xml"
  tags: 
    path: "feeds/"
